### ISSUE TITLE
iOS 10.2 support

### ISSUE THREAD

**Issue by malhal** [macmade/dyld_cache_extract#4]
Opening dyld_shared_cache_armv7s from iOS 10.2 (copied using iExplorer) in the GUI and exporting NotesShared framework gave a 561.MB NotesShared file so obviously something has gone wrong.

**Comment by macmade** [comment]
Yes, I'm aware of this kind of issue, but the extracted file should be fine, event if larger than expected.

This is because the `__LINKEDIT` segment is shared by all images in the shared cache, and placed at the very end of the cache file.

So one would need to reconstruct/relink the extracted MachO file, and adjust the offsets of the concerned segments to a new `__LINKEDIT` segment.  
Pretty boring...

I unfortunately had no time for it, so I'm actually extracting all the data until the `__LINKEDIT` segment, thus producing a very large file...

Not a neat solution, I know, but this should work at least...

**Comment by malhal** [comment]
Thanks for the explanation. The file has another issue that all methods appear as redacted, a possible solution is [here](http://ant4g0nist.blogspot.co.uk/2015/04/ios-shared-cache-extraction-to-solve.html) that could be integrated.

**Comment by macmade** [comment]
Yep, but not sure I'll have enough time to look at this right now...  
Maybe wait for iOS 11... ; )

**Comment by macmade** [comment]
Closing as the project is now obsolete.  
Please take a look at https://github.com/macmade/dyld-cache-dump
