### ISSUE TITLE
Extracting macOS 11 cache file leads to "duplicate file" prompts

### ISSUE THREAD

**Issue by tempelmann** [macmade/dyld_cache_extract#7]
I'm trying to extract all 1842 items of a "dyld_shared_cache_arm64e" file, taken from a DTK with macOS 11 beta 3. Using the released app v0.1.1

When selecting them all, and choosing "Export Selected", I get many prompts about duplicate files.

Also, all files end up being 2 GB in size, which is clearly incorrect.

I get the impression that the duplicates are symlinks, and that the extractor doesn't handle these well. It should probably simply ignore them.

**Comment by macmade** [comment]
Thanks for the suggestions, I'll take a look at it.

About the incorrect file size, I'm aware of the issue.
I'm currently extracting a lot more than just the file's portion in order to keep the offsets intact in the `LINKEDIT` segment, which is shared across all files in the cache.

A perfect implementation would remap these, but I haven't found the time to do it properly yet.

**Comment by tempelmann** [comment]
I see – extracting all ~1800 files, each at 2 GB in size, is not practical for now, then.

My problem is that I was looking for a particular error msg that I'm seeing when running an app, and I wanted to find out which framework it came from, and then look at it further with Hopper. My file search revealed that the string only appears in this large dyld_shared_cache_arm64e file. That won't tell me which framework it's in, though. So, for my need, I cannot just pick one framework, because I don't know which I need. That's why I wanted to be able to extract all frameworks so that I can then do a file search in each of them to find the one I'm seeking.

I wonder if it's possible to add a string search function that'll be able to list the frameworks in which it occurs.

I've tried to run the project myself, but I get errors about missing header files and I find no docs on where to get them and where to put them. Is that something easy to solve, maybe with `brew`?

**Comment by macmade** [comment]
About the missing headers, the project uses submodules, so you need to `git submodule update --init --recursive` first, if you didn't clone recursively.

Now for your issue, this is unfortunately somehow difficult.  
If I remember correctly, when the shared cache is built, while the text (code) sections are preserved, other sections such as data or strings are merged into a single one, shared across all images.

This is because the whole cache file is mapped into memory as a whole, for convenience.  
Makes it easy for the OS to load it, but unfortunately harder to read.

Looking for a specific string would require disassembling all frameworks to find references to the string's offset - not really convenient.

**Comment by tempelmann** [comment]
`other sections such as data or strings are merged into a single one, shared across all images.`

Wow. I guess I'll give up on pursuing that particular problem then, for now. Thanks for explaining.
